# Generated by Django 5.0.6 on 2024-06-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_character_name_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
